# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('title_score', models.IntegerField()),
                ('wx_link', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
